  version: '3.7'

  services:
    web:
      build: .
      command: python app.py
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - mongo
    mongo:
      image: mongo
      restart: always
